# Lets run on the new infrastructure
sudo: false

language: python
python:
  - "2.7"

install:
  - pip install tox

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - ./scripts/prepare_server.sh
  - ./scripts/start_server.sh
  - SELENIUM_DRIVER="selenium.webdriver.Firefox" tox -e docs-strict

after_script:
  - ./scripts/teardown_server.sh

after_failure:
  - cat server.log

deploy:
  provider: pages
  local_dir: docs/_build/html
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
